### ISSUE TITLE
Proposal: cache dir instead of src and dest

### ISSUE THREAD

**Issue by cognitom** [suluke/express-middleware-rollup#1]
Hi @suluke, nice work! I like the idea behind this library, so much 👍 
After some trial, `src/dest` seems a bit redundant for me. I'm thinking another structure like below. Thoughts?

```
.
├── server.js
├── public
│   ├──index.html
│   ├── main.js # source file
│   └── lib
│       └── test.js
└── cache
    └── main.js # bundled and compiled
```

And the code could be like this:

```javascript
app.use(rollup({
  root: 'public',
  cache: 'cache'
}));
```

Pros:
- More straightforward
- We could simply remove the middleware after the native support on browsers

If you like it, I'd like to send some PRs. I also have some other ideas. Thanks 😉

**Comment by suluke** [comment]
This sounds very reasonable. We would need to serve the cached files ourselves, then, right? In line 100 where I have left the big TODO because I considered using express' static Middleware the default use case.  The `serve` option would be obsolete then, too, I think. One drawback I see here, though, is that the middleware won't give you a statically deployable directory (what was dest). We might leave this to the user's build system though. Communicating this in the readme or as an example would be good.

**Comment by cognitom** [comment]
> We would need to serve the cached files ourselves, then, right?

Yes, we do. OK, I'll send the PR around "line 100", at first 😄 

> One drawback

How about `static` option or something? We could easily switch it from `dynamic` to `static`, vice versa.

```
.
├── server.js
├── src
│   ├──index.html
│   ├── main.js # source file
│   └── lib
│       └── test.js
└── static
    ├── index.html # just a copy
    └── main.js # bundled and compiled
```

```javascript
app.use(rollup({
  root: 'src',
  dest: 'static',
  static: true,
  watch: true // I'm not sure this option is needed or not...
}));
```

**Comment by suluke** [comment]
Ok. So I think we have two usage scenarios/operating modes:

1. The user wants to use a "smart development server", but intends to put a "frozen" version on a static file server for release. In this case, the "frozen" version is what requires us to separate `src` from `dest` and disallows us to "fix" the locations of served files when serving ourselves (this is why serving ourselves is not required)
1. The user just uses our middleware as a polyfill until es6 modules become widely supported. In this case, treating the `src` directory as the served directory is **explicitly** desired.

I have no idea how a single interface that combines those two usage scenarios could look like. I would therefore suggest that we offer two option sets:
```
mode: 'compile' | 'polyfill'
cache: <path>, required // only if mode === 'polyfill'
// rest remains as is
```
What do you think? Of course, if you have a different idea, I am happy to dicuss it with you :)

**Comment by cognitom** [comment]
Thanks for the clarification!
Your suggestion sounds pretty good. `mode: 'polyfill'` is cool!

**Comment by cognitom** [comment]
@suluke I've realized that the two modes are so close and almost same. The main difference between them is just the user's motivation or attitude. I've sent a PR #5, but didn't have to change the main logics at all 😉

**Comment by cognitom** [comment]
Hi, I'm also sending some other issues, but these are just quick notes, kind of. No rush. Today I'm going to enjoy and explore the possibility of this library!

**Comment by suluke** [comment]
Since we have a `polyfill` mode now I will close this issue. Don't forget to comment on #9, though, since this also affects how the middleware behaves in this mode :)
