### ISSUE TITLE
How to serve static&cached file from different location.

### ISSUE THREAD

**Issue by danbruegge** [suluke/express-middleware-rollup#14]
Hi, my rollup init is this:
```
app.use(rollup({
    mode: 'polyfill',
    src: './',
    root: __dirname,
    cache: '../bin',
}));
app.use(express.static(path.join(__dirname, '../bin')));
```

The JS file is on  `app/base/public/js/main.js`.

My goal is, to get the main.js file from `/static/js/main.js` instead of `/base/public/js/main.js` in my html file.

How can i accomplish this?

// Edit
The same is possible with the postcss-middleware.
```
app.use('/static/css', postcssMiddleware({
    src: request => path.join(__dirname, '**/public/css', request.path),
    plugins: [ cssnext, ],
}));
```
Here i can access my css files via `/static/css/main.css`.

**Comment by suluke** [comment]
Hi! I think `mode: polyfill` is not the right one for you. Have you tried using `compile` mode (the default mode) with the `dest` option? Maybe I did't understand you correctly

**Comment by danbruegge** [comment]
Thanks for the fast response. Yes i tried with compile mode. But maybe wrong. I will try again. :)

My current solution or workaround is this one:
```
app.use('/static/js', rollup({
    mode: 'polyfill',
    src: './base/public/js',
    root: __dirname,
    cache: '../bin',
    debug: true,
}));
app.use('/static/js', express.static(path.join(__dirname, '../bin')));
```

**Comment by suluke** [comment]
I think it should work if you set the `bundleExtension` to `.js`. This only affects how a request is mapped to the entry file of you js code. 

Quick note on `serve`: This option is set to `false` by default because I'm sure the express guys have implemented a better way to get a local file into a response.

**Comment by suluke** [comment]
Ok, I'm just now seeing your glob problem. Can you elaborate on this use case?

**Comment by danbruegge** [comment]
When i use `bundleExtension: '.js'`, then my css isn't loaded.
With the `serve` option, i will check this.

A use case for the glob would be with this app structure:
```
app
    - module1
        - public
            - js
            - css
    - module2
        - public
            - js
            - css
```
I need to glob the module names. It is already done in the postcss-middleware.

Is it possible to describe in detail the options `dest` and `serve`? The readme is not so talkative about them.

And thanks for the help so far. :)

**Comment by danbruegge** [comment]
Ok, i think i found a way to accomplish what i need. Only the glob feature is missing. ;)
```
app.use('/static/js', rollup({
    src: './base/public/js',
    root: __dirname,
    debug: true,
}));
app.use('/static/js', express.static(path.join(__dirname, 'base/public/js')));
```
With this code, i can serve my js to `http://localhost:3000/static/js/main.js`.

**Comment by suluke** [comment]
I am glad you found a configuration to satisfy your needs. I have picked up your feature request and generalized it a little in #15. I will try to implement it some time when I can. I am closing this issue in favor of the other. Thanks for your feedback.

**Comment by danbruegge** [comment]
Sounds cool. Thanks. :)

Also, i think this line `app.use('/static/js', express.static(path.join(__dirname, 'base/public/js')));` is not really DRY? Because i need to write destination and source twice. It's not a big deal but maybe it is possible to avoid the extra line with express.static.
