### ISSUE TITLE
Rollup version is out of date in most recently published version

### ISSUE THREAD

**Issue by brekk** [suluke/express-middleware-rollup#16]
Hi there,

Can you publish the current state of `master` as a new version to npm? `v1.1.0` still has `rollup@^0.26.2` as its dependency, which has a bug in it (it creates a `var extends` variable which causes problems).

Thanks,

Brekk

**Comment by suluke** [comment]
Hi, and happy new year!

Sorry for taking so long to respond. I'm not spending too much time in javascript-world these days, so in addition to the holidays I also had to find motivation to refresh my knowledge on how to release a new package version. But now I finally took the few minutes required to do this and published v1.1.1. I hope everything still works as expected after this update. The semver community still seems to be discussing which version number to bump after a dependency update ([see here](https://github.com/mojombo/semver/issues/148)), but I think v1.1.1 should be the correct version for this patch.

If you run into any troubles, please open another problem report. I would also welcome any pull requests, especially ones that add new integration tests. Thank you for your feedback!
