### ISSUE TITLE
co?

### ISSUE THREAD

**Issue by cognitom** [suluke/express-middleware-rollup#4]
@suluke could you have a look at this, when you have a time?
https://github.com/cognitom/express-middleware-rollup/blob/co/lib/express-rollup.js

My attempt with [co](https://github.com/tj/co). I realized that it might make the logic simple, without *promise hell*.
If you like it I'll be pleased send a PR, though the main purpose why I started this refactoring was for just code-reading for myself 😄

For example:
```javascript
*writeBundle(code, map, dest) {
  try {
    const stats = yield fsp.stat(dirname(dest));
    if (!stats.isDirectory()) {
      throw new Error('Directory to write to does not exist (not a directory)');
    }
    yield fsp.writeFile(dest, code);
    if (map) {
      yield fsp.writeFile(`${dest}.map`, map);
    }
  } catch (err) {
    throw err;
  }
}
```

**Comment by suluke** [comment]
Hi! Thank you for your suggestions. 
Unfortunately, I don't have any practical experience with generators. My knowledge is only theoretical, so it will take me some time to wrap my head around how Co makes use of them. From what I have seen so far the code doesn't really look more concise and (from my current position) certainly not easier to understand. But give me a week or so to look at generators and Co again and I might have changed my mind. Right now I would stick with using promises. The current code structure isn't all that bad in my opinion.

**Comment by cognitom** [comment]
Thank you for your considering. Never mind. I think keeping using promise is also fine.
I understood every line now, so it doesn't matter promises or generators 😉

Let's move on to implement new features!

**Comment by suluke** [comment]
Great! I'm looking forward to seeing PRs from you :) Maybe I will find some time this week to do something on my own. At least I will try to be there if you have any questions so I can answer in a timely manner. 
I will close this issue then.
