### ISSUE TITLE
Cache missed on the second time

### ISSUE THREAD

**Issue by cognitom** [suluke/express-middleware-rollup#6]
But it's OK on the third time.

Currently the cache is only handled in `checkNeedsRebuild()` but it seems that we need to handle it in `processBundle()` or `writeBundle()`, too.
https://github.com/suluke/express-middleware-rollup/blob/master/index.js

**Comment by suluke** [comment]
Which cache are you referring to? The dependency cache or the cache file created in polyfill mode? I just fixed an issue with the dependency cache: https://github.com/suluke/express-middleware-rollup/commit/e6af73d728c1714986d076c3670d545ee6c9f17c
Do you think this will resolve the issue you described?

**Comment by cognitom** [comment]
Hi @suluke, thanks for fixing. That's what exactly I thought 😄
