### ISSUE TITLE
Discussion: Option to configure request urls the middleware responds to

### ISSUE THREAD

**Issue by suluke** [suluke/express-middleware-rollup#9]
Currently, we hard code a regex called `extRegex` to match against incoming requests' urls for decising whether or not we are responsible for handling it. This could either be a deliberate limitation, or we should implement an option to change how we distinguish between requests we respond to and other requests.

**Comment by suluke** [comment]
I think we can safely implement this if we make it configurable via an `autoCreateDirectories` option. This option could be off by default in compile mode but on in polyfill mode or something. And of course we can have the users decide whether they are ok with the directories being created.

**Comment by cognitom** [comment]
At this point, `.js` is enough option for me.
I agree that there're potential needs for transpiling `.ts`, `.jsx` or something directly, too. But with the current Rollup implementation, it would be a bit complicated, wouldn't it?
